import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Head, Layout, Navbar } from '@components/common'
import type { AppProps } from 'next/app'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, Component, pageProps
}: {
  children: React.ReactNode
  } & AppProps) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className} style={{ width:"100%", backgroundColor: "white" }} >
        <Navbar />
        <main className="fit">{children}</main>
      </body>
    </html>
  )
}
