import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { material } from '@acme/ui/'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Next.js</title>
      </head>
      <body className={inter.className} style={{ width:"100%", backgroundColor: "white" }} >
        <div
          className={'header'}
        >From layout</div>
        <div style={{ width:"100%", backgroundColor: "white" }}>
          {children}
        </div>
        <footer>
          a foot
        </footer>
      </body>
    </html>
  )
}
